language: python
python:
  - '3.9'

# safelist
branches:
  only:
    - dev
  # command to install dependencies
before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="app.settings"

# command to run tests
script:
  - python manage.py test
