# Generated by Django 3.2.4 on 2021-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
