# Generated by Django 3.2.4 on 2021-06-25 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutriscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=150, unique=True)),
                ('brand', models.CharField(blank=True, default=False, max_length=150)),
                ('stores', models.CharField(blank=True, default=False, max_length=150)),
                ('url', models.CharField(blank=True, default=False, max_length=255, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='purbeurre.Category')),
                ('nutriscore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.nutriscore')),
            ],
        ),
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='purbeurre.product')),
                ('substituted', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='substituted', to='purbeurre.product')),
            ],
        ),
    ]
