# Generated by Django 3.2.4 on 2021-07-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurre.nutriscore'),
        ),
    ]
