# Generated by Django 3.2.4 on 2021-07-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0006_auto_20210723_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitutes',
            name='substitute',
        ),
        migrations.RemoveField(
            model_name='substitutes',
            name='substituted',
        ),
        migrations.AddField(
            model_name='substitutes',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='purbeurre.product'),
        ),
        migrations.AddField(
            model_name='substitutes',
            name='reference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='purbeurre.product'),
        ),
    ]
