# Generated by Django 3.2.4 on 2021-08-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0011_alter_product_nutriments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
    ]
