# Generated by Django 3.2.4 on 2021-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0012_remove_product_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=False, max_length=180),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=250, unique=True),
        ),
    ]
